<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="gank" name="auto.sysapi.test.demo2" tests="2" failures="0" timestamp="23 Jan 2017 02:42:17 GMT" time="99.592" errors="1">
  <testcase name="demo" time="41.875" classname="auto.sysapi.test.demo2"/>
  <testcase name="demo" time="57.717" classname="auto.sysapi.test.demo2">
    <error type="java.lang.AssertionError" message="webflg is:true||androidflg is:false||dataflg is:true expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: webflg is:true||androidflg is:false||dataflg is:true expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at auto.sysapi.test.demo2.demo(demo2.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- demo -->
</testsuite> <!-- auto.sysapi.test.demo2 -->
